######################################################################
# Automatically generated by qmake (2.01a) sø 20. apr 19:15:10 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl network

# Input
SOURCES += HDAPS_Client.cpp HDAPS_GLWidget.cpp HDAPS_NetworkListener.cpp 
HEADERS += HDAPS_GLWidget.h HDAPS_NetworkListener.h 
